USE notapp-db;

CREATE TABLE users(
	id CHAR(36) NOT NULL,
	username VARCHAR(250) NOT NULL,
	email VARCHAR(250) NOT NULL,
	name VARCHAR(250) NOT NULL,
	lastname VARCHAR(250) NOT NULL,
	password VARCHAR(250) NOT NULL,
	salt VARCHAR(250) NOT NULL,

	-- KEYS
	PRIMARY KEY( id )
) ENGINE = InnoDB CHARSET = utf8;

CREATE TABLE categories(
	id CHAR(36) NOT NULL,
	name VARCHAR(250) NOT NULL,

	-- KEYS
	PRIMARY KEY( id )
) ENGINE = InnoDB CHARSET = utf8;

CREATE TABLE notes(
	id CHAR(36) NOT NULL,
	title VARCHAR(250) NOT NULL,
	body VARCHAR(250) NOT NULL,
	category CHAR(36) NOT NULL,
	owner CHAR(36) NOT NULL,

	-- KEYS
	PRIMARY KEY( id ),
	FOREIGN KEY( category ) REFERENCES categories( id )
    		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY( owner ) REFERENCES users( id )
    		ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB CHARSET = utf8;